(fix) generate a checksum on encrpytion, fix the verify and decrypt scripts

diff --git a/bin/encrypt-file b/bin/encrypt-file
--- a/bin/encrypt-file
+++ b/bin/encrypt-file
@@ -2,11 +2,21 @@
 
 CRYPTO_FILE=$HOME/.crypto.sh
 
+FILE=$2
+
 if [[ -f $CRYPTO_FILE  ]]
 then
   source $CRYPTO_FILE
 else
   echo "WARNING: no default $CRYPTO_FILE file"
+fi
+
+if shasum -a 512 $FILE >${FILE}.sha512
+then
+  echo "sha512 checksum generated to: ${FILE}.sha512"
+else
+  echo "Error! checksum generation for $FILE FAILED!"
+  exit 1
 fi
 
 if [[ -n "$2" ]]
@@ -16,7 +26,7 @@ else
   KEY=$DEFAULT_ENCRYPTION_KEY
 fi
 
-if gpg --recipient $KEY --output ${1}.gpg --encrypt --armor $1
+if gpg --recipient $KEY --output ${FILE}.gpg --encrypt --armor $FILE
 then
   echo "encryption ok."
 else
diff --git a/bin/verify-file b/bin/verify-file
--- a/bin/verify-file
+++ b/bin/verify-file
@@ -1,17 +1,32 @@
 #! /usr/bin/env bash
 
-if shasum -c ${1}.sha512
-then
-  echo "shasum ok."
+checksum="${1}.sha512"
+signature="${1}.sig"
+
+if [[ -f $checksum ]]
+  if shasum -c $checksum
+  then
+    echo "sha512 ok."
+  else
+    echo "sha512 FAILED!"
+    exit 1
+  fi
 else
-  echo "shasum FAILED!"
+  echo >/dev/stderr "Warning! no checksum found."
 fi
 
-if gpg --verify ${1}.sig ${1}
+if [[ -f $signature ]]
 then
-  echo "valid signature."
+  if gpg --verify $signature
+  then
+    echo "valid signature."
+    exit 0
+  else
+    echo "BAD SIGNATURE!"
+    exit 1
+  fi
 else
-  echo "BAD SIGNATURE!"
+  echo >/dev/stderr "Warning! no signature found."
 fi
 
 
